"""Pre-debate research — builds a shared market-state packet that all specialists see.

The packet is generated by invoking Claude Code with WebSearch and WebFetch
enabled, given a researcher system prompt and the debate topic. The output is
a concise markdown brief covering current price, recent flows, positioning,
calendar, vol state, and key headlines. It is pinned to the transcript so every
specialist reasons from the same factual baseline.

This is separate from per-specialist tool use: specialists may *also* search the
web during their own turn (if their frontmatter allows it) to chase whatever
their lens prioritizes. The packet is the common context; per-specialist search
is the specialized follow-up.
"""
from __future__ import annotations
from .backends import get_backend
from .backends.base import BackendResponse


RESEARCHER_SYSTEM_PROMPT = """You are a market-state researcher producing a pre-debate briefing
packet for an FX swing-trading council (6 specialists with different lenses,
chaired by a moderator). The council will hold a structured debate based on
your packet, so your job is to give them a tight, factual snapshot of the
market state for the topic they are about to debate.

Use WebSearch and WebFetch to gather current information. Prioritize
authoritative sources (CFTC for COT, central bank pages, ForexFactory or
Investing.com calendars, major bank research summaries, Reuters/Bloomberg
headlines). If the topic mentions a specific FX pair, focus on that pair and
its two constituent currencies.

Output a single markdown document with these sections, in this order:

## Spot snapshot
- Current price, 1-day / 1-week / 1-month change
- Recent range, key nearby technical levels (prior swing highs/lows)
- Any unusual flow notes from the last 24-48h

## Rate & monetary policy backdrop
- Current policy rate of each currency in the pair
- Market-implied path (next CB meeting, OIS-implied probability if you can find it)
- Most recent CB statement / minutes key takeaway
- 2y and 10y yield differential, current level and direction

## Macro data — recent and upcoming
- Last major prints (CPI, NFP/employment, GDP, PMIs) and surprise vs consensus
- Upcoming scheduled events inside a typical swing-holding window (1 day to 2 weeks ahead)
- Anything on the geopolitical / fiscal calendar that matters

## Positioning & sentiment
- Latest CFTC COT large-spec net positioning for the relevant currency futures, with percentile context if available
- Retail positioning if visible (IG sentiment, MyFXBook aggregate)
- Risk regime: VIX level and direction, S&P 500 1-week move, JPY/CHF behavior

## Cross-asset / intermarket
- DXY level and 1-week direction
- US10Y and 2s10s curve current state
- Relevant commodity (oil for CAD, copper/iron for AUD, gold for risk-off)
- Any notable correlation breaks worth flagging

## Volatility state
- 1-month implied vol for the pair (or G10 average if not found)
- ATR or realized vol relative to its recent range (high / mid / low regime)
- Options skew or risk reversal if available

## Notable headlines (last 7 days)
- 3-6 bullet points, each with a one-line summary. Source name in parentheses.

## Researcher notes
- Anything you searched for and couldn't find — be explicit so the council knows what's missing.
- Caveats about data freshness (e.g., COT lags by several days).

Constraints:
- Keep the entire packet under ~1500 words.
- Cite numbers, not vibes. "DXY at 104.20" beats "DXY is firm."
- If you find conflicting data points, report both and flag the conflict.
- DO NOT take a directional view. You are the researcher; the specialists decide.
"""


def build_research_packet(
    topic: str,
    decisions: list[str],
    model: str = "sonnet",
    backend_mode: str = "claude_code",
    console=None,
) -> tuple[str, BackendResponse]:
    """Build a pre-debate research packet for the given topic.

    Returns (packet_markdown, BackendResponse). The response carries cost and
    duration metadata so the orchestrator can record it on the Transcript.
    """
    backend = get_backend(backend_mode)
    decision_list = "\n".join(f"- {d}" for d in decisions)
    user_prompt = (
        f"TOPIC THE COUNCIL WILL DEBATE:\n{topic}\n\n"
        f"DECISIONS THE MODERATOR MUST RESOLVE:\n{decision_list}\n\n"
        f"Produce the pre-debate research packet now, using WebSearch and "
        f"WebFetch as needed. Output the markdown packet only — no preamble."
    )
    if console is not None:
        console.print("[research] Building pre-debate market-state packet…")
    else:
        print("[research] Building pre-debate market-state packet…")

    resp = backend.call(
        system_prompt=RESEARCHER_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        model=model,
        tools_allowed=["WebSearch", "WebFetch"],
    )
    return resp.text.strip(), resp
